let productos = [
  { id: 1, categoria: "cervezas", nombre: "Cerveza Palermo", precio: 300, cantidad: 1, stock: 12, img: "https://jumboargentina.vtexassets.com/arquivos/ids/203973/Cerveza-Palermo-Cerveza-Retornable-Palermo-1-L-1-40366.jpg?v=636383660003330000", descripcion: "Cerveza Palermo es una cerveza estilo lager. Es elaborada en base a una selección de las mejores materias primas para lograr una cerveza suave, refrescante y única." },
  { id: 2, categoria: "vinos",nombre: "Las Perdices Malbec", precio: 1300, cantidad: 1, stock: 6, img: "https://cepadevinos.com/wp-content/uploads/2017/07/Las_Perdices_Reserva_Don_Juan_tw5nxq.jpg", descripcion:"Color rojo violáceo intenso. De complejos aromas a frutas rojas, con delicados toques de madera. Suave en boca, equilibrado, con notas de ciruelas y guindas. Ideal para acompañar carnes rojas, pastas o pescados y carnes blancas con salsas especiadas." },
  { id: 3, categoria: "aperitivos",nombre: "Cinzano", precio: 800, cantidad: 1, stock: 10, img: "https://www.espaciovino.com.ar/media/default/0001/66/thumb_65367_default_medium.jpeg", descripcion:"De brillante color ámbar oscuro, Cinzano Rosso es un vermut rojo. Posee un aroma intenso y atractivo, con presencia de vainilla, hierbas, flores y especias que son parte de su fórmula secreta. En boca es suave y dulce, con un final con agradables notas amargas, típicas de la artemisia y caramelo." },
  { id: 4, categoria: "whiskys",nombre: "Jack Daniels", precio: 5000, cantidad: 1, stock: 5, img: "https://images.shopdutyfree.com/image/upload//v1531318313/020/004/005/2028251670023/2028251670023_1_default_default.jpg", descripcion:"Este tipo de whisky se caracteriza por ser elaborado como un bourbon, Posee un sabor dulce, debido a los barriles donde es añejado, ya que al probarlo te ofrece un deleite de sabores que le otorgan el maíz, el centeno y la malta." },
  { id: 5, categoria: "aperitivos",nombre: "Gin Tanqueray", precio: 2000, cantidad: 1, stock: 8, img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/871/106/products/tanqueray1-3826edd2b1142ed2f815882515213427-1024-1024.jpg", descripcion:"Desde su creación por Charles Tanqueray en la década de 1830, la ginebra Tanqueray London Dry Gin siempre ha utilizado la misma receta galardonada* y se elabora con los cuatro ingredientes botánicos clásicos de la ginebra: enebro con aroma a pino, cilantro especiado, angélica aromática y regaliz dulce." },
  { id: 6, categoria: "aperitivos",nombre: "Campari", precio: 700, cantidad: 1, stock: 7, img: "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/395/170/products/campari-7501-ba2b8a274c5402701116385680548449-1024-1024.png", descripcion:"Campari es una bebida espirituosa obtenida de la infusión de plantas aromáticas de hierbas amargas y frutas en alcohol y agua. Con su vibrante color rojo, intenso aroma y sabor inspirador." },
  { id: 7, categoria: "aperitivos",nombre: "Fernet Branca", precio: 1300, cantidad: 1, stock: 17, img: "https://labebidadetusfiestas.com.ar/37266-thickbox_default/fernet-branca-1lt.jpg", descripcion:"Fernet-Branca es de color marrón claro con reflejos ámbar y desprende un aroma a menta que predomina sobre el resto de las hierbas con las que se elabora, aunque debajo de la menta se percibe pino, algunas notas florales y hasta caramelo." },
  { id: 8, categoria: "otros",nombre: "Coca-Cola", precio: 350, cantidad: 1, stock: 24, img: "https://roldanonline.com.ar/wp-content/uploads/2020/07/7790895063794.jpg", descripcion:"Coca-Cola, es una bebida azucarada gaseosa vendida a nivel mundial. El distintivo sabor a cola proviene en su mayoría de la mezcla de azúcar y aceites de naranja, limón y vainilla." },
  { id: 9, categoria: "otros",nombre: "Jugo Citric", precio: 280, cantidad: 1, stock: 15, img: "https://kikimarket.com.ar/wp-content/uploads/2021/09/citric-jujo-naranja-con-pulpa-1-lt-kiki-market-tienda-natural-dietetica-herboristeria-villa-carlos-paz-min.jpg", descripcion:"Citric es jugo 100% exprimido, con el sabor y la pulpa natural de la fruta. No tiene azúcar ni otros agregados artificiales." },
  { id: 10, categoria: "cervezas", nombre: "Cerveza Miller", precio: 370, cantidad: 1, stock: 24, img: "https://static.wixstatic.com/media/d2b1c5_6fde8aa14776464796ffa4b5a9eaac2e~mv2.png/v1/fill/w_1000,h_1000,al_c/d2b1c5_6fde8aa14776464796ffa4b5a9eaac2e~mv2.png", descripcion: "La Cerveza Miller, es una cerveza americana de tipo lager, suave y fácil de beber. De contenido alcohólico moderado y combinado con su punto amargo, hacen que esta cerveza sea una de las mas refrescantes dentro de su segmento."},
  { id: 11, categoria: "cervezas", nombre: "Cerveza Stella", precio: 450, cantidad: 1, stock: 36, img: "https://static.wixstatic.com/media/d2b1c5_62629d96d63a4ceaaf92481bb25ef628~mv2.jpg/v1/fill/w_1000,h_1000,al_c,q_85/d2b1c5_62629d96d63a4ceaaf92481bb25ef628~mv2.jpg", descripcion: "Lager de color dorado pálido, muy brillante y con una espuma consistente. Una cerveza muy equilibrada donde predominan moderadas notas a frutas blancas y de cereal que resaltan levemente sobre el aroma herbal del lúpulo Saaz. En boca presenta una sensación suave, ligera de amargo y con efecto refrescante."},
  { id: 12, categoria: "vinos",nombre: "Trumpeter Malbec", precio: 2100, cantidad: 1, stock: 12, img: "https://www.espaciovino.com.ar/media/default/0001/62/thumb_61963_default_big.jpeg", descripcion:"De un impactante color violeta. Nariz frutal destacando ciruelas, cerezas y notas florales que nos recuerdan a las violetas. Posee gran cuerpo y su vivaz estructura acentúa sus taninos intensos que se vuelven aterciopelados en el retrogusto."},
  { id: 13, categoria: "whiskys",nombre: "Jameson Ipa", precio: 3500, cantidad: 1, stock: 8, img: "http://inspiravinoteca.com/web/image/product.template/6271/image_1024?unique=2e1179f", descripcion:"Jameson Caskmates IPA es un whiskey irlandés añejado en barricas impregnados de Pale Ale irlandesa. Su sabor es a lúpulo y cítricos suaves con notas de hierbas dulces y delicados tonos especiados. La persistencia de la fruta fresca y el lúpulo dan paso a los granos de cebada y a su acabado suave y característico."},
  { id: 14, categoria: "otros",nombre: "Schweppes Tonica", precio: 320, cantidad: 1, stock: 12, img: "https://carrefourar.vtexassets.com/arquivos/ids/254381/7790895006715_02.jpg?v=637970559082770000", descripcion:"Schweppes es una gaseosa con un sabor único, con carácter y sutiles burbujas y muy refrescante. Ideal para disfrutar sus distintos sabores en ocasiones sociales y de disfrute, para explorar y saborear las experiencias de la vida."},
  { id: 15, categoria: "vinos",nombre: "Rutini Sauvignon Blanc", precio: 2800, cantidad: 1, stock: 4, img: "https://www.espaciovino.com.ar/media/default/0001/63/thumb_62009_default_medium.jpeg", descripcion:"Amarillo brillante, con reflejos verdosos. Intensamente aromático, de carácter cítrico que recuerda al pomelo rosado y algunos toques herbáceos. Frutado y fresco en boca, la fugaz nota robliza debida a su breve crianza en madera lo convierte en un blanco equilibrado y singular."},
];

export const gFetch = () => {
  return new Promise((resolve, reject) => {
    resolve(productos)
  });
};

