let productos = [
    { id: 1, categoria: "cervezas", nombre: "Cerveza Palermo", precio: 300, cantidad: 1, img: "https://jumboargentina.vtexassets.com/arquivos/ids/203973/Cerveza-Palermo-Cerveza-Retornable-Palermo-1-L-1-40366.jpg?v=636383660003330000", descripcion: "Cerveza Palermo es una cerveza estilo lager. Es elaborada en base a una selección de las mejores materias primas para lograr una cerveza suave, refrescante y única." },
    { id: 2, categoria: "vinos",nombre: "Las Perdices Malbec", precio: 1300, cantidad: 1, img: "https://cepadevinos.com/wp-content/uploads/2017/07/Las_Perdices_Reserva_Don_Juan_tw5nxq.jpg", descripcion:"Color rojo violáceo intenso. De complejos aromas a frutas rojas, con delicados toques de madera. Suave en boca, equilibrado, con notas de ciruelas y guindas. Ideal para acompañar carnes rojas, pastas o pescados y carnes blancas con salsas especiadas." },
    { id: 3, categoria: "aperitivos",nombre: "Cinzano", precio: 800, cantidad: 1, img: "https://www.espaciovino.com.ar/media/default/0001/66/thumb_65367_default_medium.jpeg", descripcion:"De brillante color ámbar oscuro, Cinzano Rosso es un vermut rojo. Posee un aroma intenso y atractivo, con presencia de vainilla, hierbas, flores y especias que son parte de su fórmula secreta. En boca es suave y dulce, con un final con agradables notas amargas, típicas de la artemisia y caramelo." },
    { id: 4, categoria: "whiskys",nombre: "Jack Daniels", precio: 5000, cantidad: 1, img: "https://images.shopdutyfree.com/image/upload//v1531318313/020/004/005/2028251670023/2028251670023_1_default_default.jpg", descripcion:"Este tipo de whisky se caracteriza por ser elaborado como un bourbon, Posee un sabor dulce, debido a los barriles donde es añejado, ya que al probarlo te ofrece un deleite de sabores que le otorgan el maíz, el centeno y la malta." },
    { id: 5, categoria: "aperitivos",nombre: "Gin Tanqueray", precio: 2000, cantidad: 1, img: "https://whiskypedia.com.ar/wp-content/uploads/2020/10/tanqueray-london-dry-gin-742775.jpg", descripcion:"Desde su creación por Charles Tanqueray en la década de 1830, la ginebra Tanqueray London Dry Gin siempre ha utilizado la misma receta galardonada* y se elabora con los cuatro ingredientes botánicos clásicos de la ginebra: enebro con aroma a pino, cilantro especiado, angélica aromática y regaliz dulce." },
    { id: 6, categoria: "aperitivos",nombre: "Campari", precio: 700, cantidad: 1, img: "http://d3ugyf2ht6aenh.cloudfront.net/stores/972/269/products/campari-750ml1-bfdd36021f07a23e4b15627824841405-640-0.jpg", descripcion:"Campari es una bebida espirituosa obtenida de la infusión de plantas aromáticas de hierbas amargas y frutas en alcohol y agua. Con su vibrante color rojo, intenso aroma y sabor inspirador." },
    { id: 7, categoria: "aperitivos",nombre: "Fernet Branca", precio: 1300, cantidad: 1, img: "https://labebidadetusfiestas.com.ar/37266-thickbox_default/fernet-branca-1lt.jpg", descripcion:"Fernet-Branca es de color marrón claro con reflejos ámbar y desprende un aroma a menta que predomina sobre el resto de las hierbas con las que se elabora, aunque debajo de la menta se percibe pino, algunas notas florales y hasta caramelo." },
    { id: 8, categoria: "otros",nombre: "Coca-Cola", precio: 350, cantidad: 1, img: "https://roldanonline.com.ar/wp-content/uploads/2020/07/7790895063794.jpg", descripcion:"Coca-Cola, es una bebida azucarada gaseosa vendida a nivel mundial. El distintivo sabor a cola proviene en su mayoría de la mezcla de azúcar y aceites de naranja, limón y vainilla." },
    { id: 9, categoria: "otros",nombre: "Jugo Citric", precio: 280, cantidad: 1, img: "https://kikimarket.com.ar/wp-content/uploads/2021/09/citric-jujo-naranja-con-pulpa-1-lt-kiki-market-tienda-natural-dietetica-herboristeria-villa-carlos-paz-min.jpg", descripcion:"Citric es jugo 100% exprimido, con el sabor y la pulpa natural de la fruta. No tiene azúcar ni otros agregados artificiales." },
];

export const gFetch = () => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(productos)
      }, 2000);
    })
  }